name: optr
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  google_fonts: ^1.1.0
  simple_animations: ^2.2.1
  drawing_animation: ^0.1.3
  sa_stateless_animation: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0
  device_info: ^0.4.2+4
  intl: ^0.16.1
  soundpool: ^1.1.1
  flutter_secure_storage: ^3.3.3
  hooks_riverpod: ^0.1.0
  barcode: ^1.13.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  uuid: ^2.1.0
  crypto: ^2.1.5
  animations: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/word_icon.hive
